HUNT_FILE = "/home/pi/hunt/hunt_data"

# SECOND_MS = 997  # 1000 ms/second adjusted for drift on MAC
MINUTE = 60
HOUR = 60 * MINUTE
EMERGENCY_PENALTY = 20 * MINUTE
TOTAL_HUNT_TIME = 5 * HOUR + 15 * MINUTE
TIMER_REFRESH = 250

CLUE_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
CLUE_STATUS = ["Not Found", "Solved", "Emergency", "Half Credit"]
STATUS_COLORS = {
    "Not Found": "grey",
    "Solved": "green",
    "Emergency": "yellow",
    "Half Credit": "medium turquoise",
}

UNSPECIFIED = "--"

MAIN_BG = "black"
HIGHLIGHT_BG = "grey"
INFO_COLOR = "green"
LABEL_COLOR = "grey"
SELECTABLE_COLOR = "grey"
NOT_SELECTABLE_COLOR = "grey18"

INFO_WIDTH = 6
INFO_TEXT_SIZE = 29
LABEL_TEXT_SIZE = 12


FRAME = "ridge"
FONT = "Helvetica"
BD_SIZE = 3
PADX = 2
PADY = 2

BLINK_TIME = 500

CANVAS_WIDTH = 620
CANVAS_HEIGHT = 300
GRAPH_CENTER_X = 3 * (CANVAS_WIDTH / 4)
GRAPH_CENTER_Y = CANVAS_HEIGHT - (CANVAS_HEIGHT / 2)
GRAPH_INFO_OFFSET = 90
SCALE_REFERENCE = 200
POINT_LABEL_COLOR = "white"
DEFAULT_LINE_COLOR = "grey"
DEFAULT_LINE_WIDTH = 2
INVALID_LINE_COLOR = "red"
INITIALIZED_LINE_COLOR = "green"
SCALE_LABEL_OFFSET = 40
DEF_CLUE_OFFSET = 50

COMPASS_DISPLAY_PERIOD = 200
COMPASS_CENTER_X = CANVAS_WIDTH / 4
COMPASS_CENTER_Y = CANVAS_HEIGHT - (CANVAS_HEIGHT / 2)
DIAL_OUTER = 60
DIAL_INNER = DIAL_OUTER - 20
BEZEL_RADIUS = DIAL_OUTER - (1 / 2 * (DIAL_OUTER - DIAL_INNER))
DIAL_COLOR = "DodgerBlue4"
TRAVEL_ARROW_TIP = (0, DIAL_INNER)
TRAVEL_ARROW_COLOR = "grey"
TA_TAIL_ANGLE = 165
CLUE_VECTOR_LENGTH = DIAL_OUTER + 15
ARROWSHAPE = (5, 10, 3)
CLUE_CIRCLE_RADIUS = 35
CLUE_VECTOR_COLOR = "green"

TOUCH_BOX_SIZE = 40
MARKER_RADIUS = 20
FOCUS_COLOR = "white"
DEFOCUS_COLOR = "grey"
GRAPH_WIDGET_TEXT_SIZE = 25
DEFAULT_M = ((0, -SCALE_REFERENCE / 2),)
DEFAULT_P = ((0, SCALE_REFERENCE / 2),)
DEFAULT_C = ((SCALE_REFERENCE / 2, SCALE_REFERENCE / 2),)

TABLE_X = 150
TABLE_Y = -50
ROW = -30
