HUNT_FILE = "./hunt_data"

SECOND_MS = 997  # 1000 ms/second adjusted for drift on MAC
MINUTE = 60
HOUR = 60 * MINUTE
EMERGENCY_PENALTY = 20 * MINUTE
TOTAL_HUNT_TIME = 5 * HOUR + 15 * MINUTE
TIMER_REFRESH = 250

CLUE_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
CLUE_STATUS = ["Not Found", "Solved", "Emergency", "Half Credit", "Parked"]
STATUS_COLORS = {
    "Not Found": "grey",
    "Solved": "green",
    "Emergency": "yellow",
    "Half Credit": "orange",
    "Parked": "blue",
}

UNSPECIFIED = "--"

MAIN_BG = "black"
HIGHLIGHT_BG = "grey"
INFO_TEXT_COLOR = "green"
LABEL_TEXT_COLOR = "grey"
ENTRY_TEXT_COLOR = "grey"

INFO_WIDTH = 6
INFO_TEXT_SIZE = 29
LABEL_TEXT_SIZE = 12
# VECTOR_TEXT_SIZE = 12


FRAME = "ridge"
FONT = "Helvetica"
# LARGE_FONT = 29
# SMALL_FONT = 12
BD_SIZE = 3
PADX = 2
PADY = 2

BLINK_TIME = 500

CANVAS_WIDTH = 550
CANVAS_HEIGHT = 250
GRAPH_CENTER_X = 3 * (CANVAS_WIDTH / 4)
GRAPH_CENTER_Y = CANVAS_HEIGHT - (CANVAS_HEIGHT / 2)
GRAPH_INFO_OFFSET = 90
# V_CENTER_SCX = -120
# V_CENTER_SCY = CANVAS_HEIGHT / 2 - 10
SCALE_REFERENCE = 100
POINT_LABEL_COLOR = "white"
DEFAULT_LINE_COLOR = "grey"
DEFAULT_LINE_WIDTH = 2
INITIALIZED_LINE_COLOR = "green"
SCALE_LABEL_OFFSET = 20
DEF_CLUE_OFFSET = 50


COMPASS_CENTER_X = CANVAS_WIDTH / 4
COMPASS_CENTER_Y = CANVAS_HEIGHT - (CANVAS_HEIGHT / 2)
DIAL_OUTER = 55
DIAL_INNER = DIAL_OUTER - 20
BEZEL_RADIUS = DIAL_OUTER - (1 / 2 * (DIAL_OUTER - DIAL_INNER))
DIAL_COLOR = "grey"
TRAVEL_ARROW_TIP = (0, DIAL_INNER)
TRAVEL_ARROW_COLOR = "grey"
TA_TAIL_ANGLE = 165
CLUE_VECTOR_LENGTH = DIAL_OUTER + 15
ARROWSHAPE = (5, 10, 3)
CLUE_CIRCLE_RADIUS = 25
CLUE_VECTOR_COLOR = "green"
